urls.py
import os.path
from django.conf.urls.defaults import *
from django.contrib import admin
from forum.views import index
from forum import views as app
from forum.feed import RssLastestQuestionsFeed

admin.autodiscover()
feeds = {
    'rss': RssLastestQuestionsFeed
}

APP_PATH = os.path.dirname(__file__)
urlpatterns = patterns('',
    (r'^$', index),
    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/content/images/favicon.ico'}),
    (r'^favicon\.gif$', 'django.views.generic.simple.redirect_to', {'url': '/content/images/favicon.gif'}),
    (r'^content/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': os.path.join(APP_PATH, 'templates/content').replace('\\','/')}
    ),
    (r'^upfiles/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': os.path.join(APP_PATH, 'templates/upfiles').replace('\\','/')}
    ),
    (r'^account/', include('django_authopenid.urls')),
    (r'^signin/$', 'django_authopenid.views.signin'),
    url(r'^email/change/$', 'django_authopenid.views.changeemail', name='user_changeemail'),
    url(r'^email/sendkey/$', 'django_authopenid.views.send_email_key'),
    url(r'^email/verify/(?P<id>\d+)/(?P<key>[\dabcdef]{32})/$', 'django_authopenid.views.verifyemail', name='user_verifyemail'),
    url(r'^about/$', app.about, name='about'),
    url(r'^faq/$', app.faq, name='faq'),
    url(r'^privacy/$', app.privacy, name='privacy'),
    url(r'^logout/$', app.logout, name='logout'),
    url(r'^answers/(?P<id>\d+)/comments/$', app.answer_comments, name='answer_comments'),
    url(r'^answers/(?P<id>\d+)/edit/$', app.edit_answer, name='edit_answer'),
    url(r'^answers/(?P<id>\d+)/revisions/$', app.answer_revisions, name='answer_revisions'),
    url(r'^questions/$', app.questions, name='questions'),
    url(r'^questions/ask/$', app.ask, name='ask'),
    url(r'^questions/unanswered/$', app.unanswered, name='unanswered'),
    url(r'^questions/(?P<id>\d+)/edit/$', app.edit_question, name='edit_question'),
    url(r'^questions/(?P<id>\d+)/close/$', app.close, name='close'),
    url(r'^questions/(?P<id>\d+)/reopen/$', app.reopen, name='reopen'),
    url(r'^questions/(?P<id>\d+)/answer/$', app.answer, name='answer'),
    url(r'^questions/(?P<id>\d+)/vote/$', app.vote, name='vote'),
    url(r'^questions/(?P<id>\d+)/revisions/$', app.question_revisions, name='question_revisions'),
    url(r'^questions/(?P<id>\d+)/comments/$', app.question_comments, name='question_comments'),
    url(r'^questions/(?P<question_id>\d+)/comments/(?P<comment_id>\d+)/delete/$', app.delete_question_comment, name='delete_question_comment'),
    url(r'^answers/(?P<answer_id>\d+)/comments/(?P<comment_id>\d+)/delete/$', app.delete_answer_comment, name='delete_answer_comment'),
    #place general question item in the end of other operations
    url(r'^questions/(?P<id>\d+)//*', app.question, name='question'),
    (r'^tags/$', app.tags),
    (r'^tags/(?P<tag>[^/]*)/$', app.tag),
    (r'^users/$',app.users),
    url(r'^users/(?P<id>\d+)/edit/$', app.edit_user, name='edit_user'),
    url(r'^users/(?P<id>\d+)//*', app.user, name='user'),
    url(r'^badges/$',app.badges, name='badges'),
    url(r'^badges/(?P<id>\d+)//*', app.badge, name='badge'),
    url(r'^messages/markread/$',app.read_message, name='read_message'),
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^nimda/(.*)', admin.site.root),
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
    (r'^upload/$', app.upload),
    url(r'^books/$', app.books, name='books'),
    url(r'^books/ask/(?P<short_name>[^/]+)/$', app.ask_book, name='ask_book'),
    url(r'^books/(?P<short_name>[^/]+)/$', app.book, name='book'),
    url(r'^search/$', app.search, name='search'),
    (r'^i18n/', include('django.conf.urls.i18n')),
)

django_authopenid/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

import hashlib, random, sys, os, time

__all__ = ['Nonce', 'Association', 'UserAssociation', 
        'UserPasswordQueueManager', 'UserPasswordQueue']

class Nonce(models.Model):
    """ openid nonce """
    server_url = models.CharField(max_length=255)
    timestamp = models.IntegerField()
    salt = models.CharField(max_length=40)
    
    def __unicode__(self):
        return u"Nonce: %s" % self.id

    
class Association(models.Model):
    """ association openid url and lifetime """
    server_url = models.TextField(max_length=2047)
    handle = models.CharField(max_length=255)
    secret = models.TextField(max_length=255) # Stored base64 encoded
    issued = models.IntegerField()
    lifetime = models.IntegerField()
    assoc_type = models.TextField(max_length=64)
    
    def __unicode__(self):
        return u"Association: %s, %s" % (self.server_url, self.handle)

class UserAssociation(models.Model):
    """ 
    model to manage association between openid and user 
    """
    openid_url = models.CharField(blank=False, max_length=255)
    user = models.ForeignKey(User, unique=True)
    
    def __unicode__(self):
        return "Openid %s with user %s" % (self.openid_url, self.user)

class UserPasswordQueueManager(models.Manager):
    """ manager for UserPasswordQueue object """
    def get_new_confirm_key(self):
        "Returns key that isn't being used."
        # The random module is seeded when this Apache child is created.
        # Use SECRET_KEY as added salt.
        while 1:
            confirm_key = hashlib.md5("%s%s%s%s" % (
                random.randint(0, sys.maxint - 1), os.getpid(),
                time.time(), settings.SECRET_KEY)).hexdigest()
            try:
                self.get(confirm_key=confirm_key)
            except self.model.DoesNotExist:
                break
        return confirm_key


class UserPasswordQueue(models.Model):
    """
    model for new password queue.
    """
    user = models.ForeignKey(User, unique=True)
    new_password = models.CharField(max_length=30)
    confirm_key = models.CharField(max_length=40)

    objects = UserPasswordQueueManager()

    def __unicode__(self):
        return self.user.username

forum/forms.py
import re
from datetime import date
from django import forms
from models import *
from const import *
from django.utils.translation import ugettext as _

class TitleField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(TitleField, self).__init__(*args, **kwargs)
        self.required = True
        self.widget = forms.TextInput(attrs={'size' : 70, 'autocomplete' : 'off'})
        self.max_length = 255
        self.label  = _('title')
        self.help_text = _('please enter a descriptive title for your question')
        self.initial = ''

    def clean(self, value):
        if len(value) < 10:
            raise forms.ValidationError(_('title must be > 10 characters'))

        return value

class EditorField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(EditorField, self).__init__(*args, **kwargs)
        self.required = True
        self.widget = forms.Textarea(attrs={'id':'editor'})
        self.label  = _('content')
        self.help_text = u''
        self.initial = ''

    def clean(self, value):
        if len(value) < 10:
            raise forms.ValidationError(_('question content must be > 10 characters'))

        return value

class TagNamesField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(TagNamesField, self).__init__(*args, **kwargs)
        self.required = True
        self.widget = forms.TextInput(attrs={'size' : 50, 'autocomplete' : 'off'})
        self.max_length = 255
        self.label  = _('tags')
        #self.help_text = _('please use space to separate tags (this enables autocomplete feature)')
        self.help_text = _('Tags are short keywords, with no spaces within. Up to five tags can be used.')
        self.initial = ''

	def clean(self, value):
		value = super(TagNamesField, self).clean(value)
		data = value.strip()
		if len(data) < 1:
			raise forms.ValidationError(_('tags are required'))
		list = data.split(' ')
		list_temp = []
		if len(list) > 5:
			raise forms.ValidationError(_('please use 5 tags or less'))
		for tag in list:
			if len(tag) > 20:
				raise forms.ValidationError(_('tags must be shorter than 20 characters'))
			#take tag regex from settings
			tagname_re = re.compile(r'[a-z0-9]+')
			if not tagname_re.match(tag):
				raise forms.ValidationError(_('please use following characters in tags: letters \'a-z\', numbers, and characters \'.-_#\''))
			# only keep one same tag
			if tag not in list_temp and len(tag.strip()) > 0:
				list_temp.append(tag)
		return u' '.join(list_temp)

class WikiField(forms.BooleanField):
    def __init__(self, *args, **kwargs):
        super(WikiField, self).__init__(*args, **kwargs)
        self.required = False
        self.label  = _('community wiki')
        self.help_text = _('if you choose community wiki option, the question and answer do not generate points and name of author will not be shown')

class EmailNotifyField(forms.BooleanField):
    def __init__(self, *args, **kwargs):
        super(EmailNotifyField, self).__init__(*args, **kwargs)
        self.required = False

class SummaryField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(SummaryField, self).__init__(*args, **kwargs)
        self.required = False
        self.widget = forms.TextInput(attrs={'size' : 50, 'autocomplete' : 'off'})
        self.max_length = 300
        self.label  = _('update summary:')
        self.help_text = _('enter a brief summary of your revision (e.g. fixed spelling, grammar, improved style, this field is optional)')

class AskForm(forms.Form):
    title  = TitleField()
    text   = EditorField()
    tags   = TagNamesField()
    wiki = WikiField()

    openid = forms.CharField(required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 40, 'class':'openid-input'}))
    user   = forms.CharField(required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    email  = forms.CharField(required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))

class AnswerForm(forms.Form):
    text   = EditorField()
    wiki   = WikiField()
    openid = forms.CharField(required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 40, 'class':'openid-input'}))
    user   = forms.CharField(required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    email  = forms.CharField(required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    email_notify = EmailNotifyField()
    def __init__(self, question, user, *args, **kwargs):
        super(AnswerForm, self).__init__(*args, **kwargs)
        self.fields['email_notify'].widget.attrs['id'] = 'question-subscribe-updates';
        if question.wiki:
            self.fields['wiki'].initial = True
        if user.is_authenticated():
            try:
                feed = EmailFeed.objects.get(feed_id=question.id, subscriber_id=user.id)
                if feed.subscriber == user and feed.content == question:
                    self.fields['email_notify'].initial = True
                    return
            except EmailFeed.DoesNotExist:
                pass
        self.fields['email_notify'].initial = False


class CloseForm(forms.Form):
    reason = forms.ChoiceField(choices=CLOSE_REASONS)

class RetagQuestionForm(forms.Form):
    tags   = TagNamesField()
    # initialize the default values
    def __init__(self, question, *args, **kwargs):
        super(RetagQuestionForm, self).__init__(*args, **kwargs)
        self.fields['tags'].initial = question.tagnames

class RevisionForm(forms.Form):
    """
    Lists revisions of a Question or Answer
    """
    revision = forms.ChoiceField(widget=forms.Select(attrs={'style' : 'width:520px'}))

    def __init__(self, post, latest_revision, *args, **kwargs):
        super(RevisionForm, self).__init__(*args, **kwargs)
        revisions = post.revisions.all().values_list(
            'revision', 'author__username', 'revised_at', 'summary')
        date_format = '%c'
        self.fields['revision'].choices = [
            (r[0], u'%s - %s (%s) %s' % (r[0], r[1], r[2].strftime(date_format), r[3]))
            for r in revisions]
        self.fields['revision'].initial = latest_revision.revision

class EditQuestionForm(forms.Form):
    title  = TitleField()
    text   = EditorField()
    tags   = TagNamesField()
    summary = SummaryField()

    def __init__(self, question, revision, *args, **kwargs):
        super(EditQuestionForm, self).__init__(*args, **kwargs)
        self.fields['title'].initial = revision.title
        self.fields['text'].initial = revision.text
        self.fields['tags'].initial = revision.tagnames
        # Once wiki mode is enabled, it can't be disabled
        if not question.wiki:
            self.fields['wiki'] = WikiField()

class EditAnswerForm(forms.Form):
    text = EditorField()
    summary = SummaryField()

    def __init__(self, answer, revision, *args, **kwargs):
        super(EditAnswerForm, self).__init__(*args, **kwargs)
        self.fields['text'].initial = revision.text

class EditUserForm(forms.Form):
    email = forms.EmailField(label=u'Email', help_text=_('this email does not have to be linked to gravatar'), required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    realname = forms.CharField(label=_('Real name'), required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    website = forms.URLField(label=_('Website'), required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    city = forms.CharField(label=_('Location'), required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    birthday = forms.DateField(label=_('Date of birth'), help_text=_('will not be shown, used to calculate age, format: YYYY-MM-DD'), required=False, widget=forms.TextInput(attrs={'size' : 35}))
    about = forms.CharField(label=_('Profile'), required=False, widget=forms.Textarea(attrs={'cols' : 60}))

    def __init__(self, user, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.fields['email'].initial = user.email
        self.fields['realname'].initial = user.real_name
        self.fields['website'].initial = user.website
        self.fields['city'].initial = user.location

        if user.date_of_birth is not None:
            self.fields['birthday'].initial = user.date_of_birth
        else:
            self.fields['birthday'].initial = '1990-01-01'
        self.fields['about'].initial = user.about
        self.user = user

    def clean_email(self):
        """For security reason one unique email in database"""
        if self.user.email != self.cleaned_data['email']:
            #todo dry it, there is a similar thing in openidauth
            if settings.EMAIL_UNIQUE == True:
                if 'email' in self.cleaned_data:
                    try:
                        user = User.objects.get(email = self.cleaned_data['email'])
                    except User.DoesNotExist:
                        return self.cleaned_data['email']
                    except User.MultipleObjectsReturned:
                        raise forms.ValidationError(_('this email has already been registered, please use another one'))
                    raise forms.ValidationError(_('this email has already been registered, please use another one'))
        return self.cleaned_data['email']

templates/authopenid/changeemail.html
{% extends "base_content.html" %}
{% load i18n %}
{% block content %}
<!-- changeemail.html action_type={{action_type}}-->
{% ifequal action_type "change" %}
    <div id="main-bar" class="headNormal">
        {% trans "Change email" %}
    </div>
    <p class="message">
    {% blocktrans %}change {{email}} info{% endblocktrans %}
    </p>
    {% if form.errors %}
    <p class="errors">{% trans "Please correct errors below:" %}<br />
        {% if form.email.errors %} 
            <span class="error">{{ form.email.errors|join:", " }}</span>
        {% endif %}
        {% if form.password.errors %} 
            <span class="error">{{ form.password.errors|join:", " }}</span>
        {% endif %}
    </p>
    {% endif %}

    {% if msg %}
    <p class="errors">{{ msg }}</p>
    {% endif %}

    <div class="aligned">
        <form action="." method="post" accept-charset="utf-8">

            <div class="form-row"><label for="id_email">{% trans "Your new Email" %}</label><br>{{ form.email }}</div>
            <!--<div class="form-row"><label for="id_password">{% trans "Password" %}</label>{{ form.password }}</div>-->
            <div class="submit-row">
                <input class="submit" type="submit" name="change_email" value="{% trans "Change email" %}">
                <input class="submit" type="submit" name="cancel" value="{% trans "Cancel" %}">
            </div>

        </form>
    </div>
{% endifequal %}
{% ifequal action_type "validate" %}
    <div id="main-bar" class="headNormal">
        {% trans "Validate email" %}
    </div>
    <p class="message">
        {% blocktrans %}validate {{email}} info{% endblocktrans %}
    </p>
{% endifequal %}
{% ifequal action_type "keep" %}
    <div id="main-bar" class="headNormal">
        {% trans "Email not changed" %}
    </div>
    <p class="message">
        {% blocktrans %}old {{email}} kept{% endblocktrans %}
    </p>
{% endifequal %}
{% ifequal action_type "done_novalidate" %}
    <div id="main-bar" class="headNormal">
        {% trans "Email changed" %}
    </div>
    <p class="message">
        {% blocktrans %}your current {{email}} can be used for this{% endblocktrans %}
    </p>
{% endifequal %}
{% ifequal action_type "validation_complete" %}
    <div id="main-bar" class="headNormal">
        {% trans "Email verified" %}
    </div>
    <p class="message">
        {% trans "thanks for verifying email" %}
    </p>
{% endifequal %}
{% ifequal action_type "key_not_sent" %}
    <div id="main-bar" class="headNormal">
        {% trans "email key not sent" %}
    </div>
    <p class="message">
        {% blocktrans %}email key not sent {{email}} change email here {{change_link}}{% endblocktrans %}
    </p>
{% endifequal %}
{% endblock %}
<!-- end changeemail.html -->

templates/authopenid/changeopenid.html
{% extends "base.html" %}
<!-- changeopenid.html -->
{% load i18n %}

{% block content %}
<div id="main-bar" class="">
    <h3>
        {% trans "Account: change OpenID URL" %}
    </h3>
</div>

<p>{% blocktrans %}This is where you can change your OpenID URL. Make sure you remember it!{% endblocktrans %}</p>
{% if form.errors %}
<p class="errors">{% trans "Please correct errors below:" %}<br />
	{% if form.openid_url.errors %} 
		<span class="error">{{ form.openid_url.errors|join:", " }}</span>
	{% endif %}


</p>
{% endif %}
{% if msg %}
	<p class="errors">{{ msg }}</p>
{% endif %}

<div class="aligned">
	<form action="." method="post" accept-charset="utf-8">

		<div id="form-row"><label for="id_openid_url">{% trans "OpenID URL:" %}</label>{{ form.openid_url }}</div>
        <p><input type="submit" value="{% trans "Change OpenID" %}"></p>

	</form>
	</div>
{% endblock %}
<!-- end changeopenid.html -->

templates/authopenid/changepw.html
{% extends "base.html" %}
<!-- changepw.html -->
{% load i18n %}

{% block head %}
		
{% endblock %}



{% block content %}
<div id="main-bar" class="">
    <h3>
        {% trans "Account: change password" %}
    </h3>
</div>
<p>{% blocktrans %}This is where you can change your password. Make sure you remember it!{% endblocktrans %}</p>
{% if form.errors %}
<p class="errors">{% trans "Please correct errors below:" %}<br />
{{ form.errors }}
</p>
{% endif %}

<div class="aligned">
	<form action="." method="post" accept-charset="utf-8">

		<div id="form-row"><label for="id_oldpw">{% trans "Current password" %}</label>{{ form.oldpw }}</div>
		<div id="form-row"><label for="id_password1">{% trans "New password" %}</label>{{ form.password1 }}</div>
		<div id="form-row"><label for="id_password2">{% trans "New password again" %}</label>{{ form.password2 }}</div>
        <p><input type="submit" value="{% trans "Change password" %}"></p>

	</form>
	</div>
{% endblock %}
<!-- end changepw.html -->

templates/authopenid/complete.html
{% extends "base_content.html" %}
<!-- complete.html -->
{% load i18n %}
{% block head %}{% endblock %}
{% block title %}{% spaceless %}{% trans "Connect your OpenID with this site" %}{% endspaceless %}{% endblock %}
{% block content %}
    <div id="main-bar" class="headNormal">
		{% trans "Connect your OpenID with your account on this site" %}
    </div>      
	<p id="completetxt" >
        <div class="message">
            {% blocktrans %}register new {{provider}} account info{% endblocktrans %}
        </div>
    	<p style="display:none">{% trans "This account already exists, please use another." %}</p>
	</p>

	{% if form1.errors %}
	<p class="errors">
        <span class="big">{% trans "Sorry, looks like we have some errors:" %}</span><br>
        <ul class="error-list">
		{% if form1.username.errors %} 
			<li><span class="error">{{ form1.username.errors|join:", " }}</span></li>
		{% endif %}
		{% if form1.email.errors %} 
			<li><span class="error">{{ form1.email.errors|join:", " }}</span></li>
		{% endif %}
        </ul>
	</p>
	{% endif %}
	{% if form2.errors %}
	<p class="errors">
        <span class="big">{% trans "Sorry, looks like we have some errors:" %}</span><br>
        <ul class="error-list">
		{% if form2.username.errors %} 
			<li><span class="error">{{ form2.username.errors|join:", " }}</span></li>
		{% endif %}
		{% if form2.password.errors %} 
			<li><span class="error">{{ form2.password.errors|join:", " }}</span></li>
		{% endif %}
       </ul>
	</p>
	{% endif %}

	<div class="login">
        <form name="fregister" action="{% url user_register %}" method="POST">
            {{ form.next }}
            <div class="form-row"><label for="id_username">{% trans "Screen name label" %}</label><br />{{ form1.username }}</div>
            <div class="form-row"><label for="id_email">{% trans "Email address label" %}</label><br />{{ form1.email }}</div>
            <div class="submit-row"><input type="submit" class="submit" name="bnewaccount" value="{% trans "create account" %}"></div>
		</form>
	</div>
	<div class="login" style="display:none">
        <form name="fverify" action="{% url user_register %}" method="POST">
            {{ form.next }}
			<fieldset style="padding:10px">
				<legend class="big">{% trans "Existing account" %}</legend>
				<div class="form-row"><label for="id_username">{% trans "user name" %}</label><br />{{ form2.username }}</div>
				<div class="form-row"><label for="id_passwordl">{% trans "password" %}</label><br />{{ form2.password }}</div>
				<!--todo double check translation from chinese 确认 = "Register" -->
				<div class="submit-row">
					<input type="submit" class="submit" name="bverify" value="{% trans "Register" %}"> 
					<a href="">{% trans "Forgot your password?" %}</a>
				</div>
			</fieldset>
		</form>
	</div>
{% endblock %}
<!-- end complete.html -->

templates/authopenid/delete.html
{% extends "base.html" %}
<!-- delete.html -->
{% load i18n %}


{% block content %}
<div id="main-bar" class="">
    <h3>
        {% trans "Account: delete account" %}
    </h3>
</div>

<p class="settings-descr">{% blocktrans %}Note: After deleting your account, anyone will be able to register this username.{% endblocktrans %}</p>
{% if form.errors %}
<p class="errors">{% trans "Please correct errors below:" %}<br />
	{% if form.confirm.errors %} 
    <span class="error">{% trans "Check confirm box, if you want delete your account." %}</span><br />
	{% endif %}
	{% if form.password.errors %} 
    <span class="error">{% trans "Password:" %} {{ form.password.errors|join:", " }}</span>
	{% endif %}
</p>
{% endif %}
{% if msg %}
<p class="errors">{% trans "Please correct errors below:" %}<br />
    <span class="error">{{ msg }}</span>
    </p>
{% endif %}
<div class="aligned">
	<form action="." method="post" accept-charset="utf-8">

        <div id="form-row"> {{ form.confirm }} {% trans "I am sure I want to delete my account." %}</div>
        <div id="form-row"><label for="id_password">{% trans "Password/OpenID URL" %}</label>{{ form.password }} {% trans "(required for your security)" %}</div>

        <p><input type="submit" value="{% trans "Delete account permanently" %}"></p>

	</form>
	</div>
{% endblock %}
<!-- end delete.html -->

templates/authopenid/failure.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
  "http://www.w3.org/TR/html4/strict.dtd">
<!-- failure.html -->
<html>
<head>
  <title>OpenID failed</title>
</head>
<body>
<h1>OpenID failed</h1>

<p>{{ message|escape }}</p>

</body>
</html><!-- end failure.html -->

templates/authopenid/signup.html
{% extends "base.html" %}
<!--signup.html-->
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Signup" %}{% endspaceless %}{% endblock %}

{% block content %}
<div id="main-bar" class="">
    <h3 >{% trans "Signup" %}</h3>

</div>
<div class="jointxt">
    <p>{% trans "We support two types of user registration: conventional username/password, and" %} <a href="{% url user_signin %}">{% trans "the OpenID method" %}</a>.</p>

    {% if form.errors %}
    
    <p class="errors">
        <span class="big">{% trans "Sorry, looks like we have some errors" %}</span><br>
        <ul class="error-list">
        {% if form.username.errors %} 
        <li><span class="error">{{ form.username.errors|join:", " }}</span></li>
        {% endif %}
        {% if form.email.errors %} 
        <li><span class="error">{{ form.email.errors|join:", " }}</span></li>
        {% endif %}
        {% if form.password2.errors %} 
        <li><span class="error">{{ form.password2.errors|join:", " }}
        </span></li>
        {% endif %}
        </ul>
    </p>
    {% endif %}
</div>
    <form action="{% url user_signup %}" method="post" accept-charset="utf-8">
        <fieldset class="fieldset">
        <legend class="big">{% trans "Conventional registration" %}</legend>	
            <div class="form-row"><label for="id_username">{% trans "choose a user name" %}:</label><br>{{ form.username }}</div>

            <div class="form-row"><label for="id_email">{% trans "your email address" %}:</label><br>{{ form.email }}</div>
            <div class="form-row"><label for="id_password1">{% trans "choose password" %}:</label><br />{{ form.password1 }}</div>
            <div class="form-row"><label for="id_password2">{% trans "retype password" %}:</label><br>{{ form.password2 }}</div>
            <div class="submit-row"><input type="submit" class="submit" value="{% trans "login" %}" > 
			<a href="{% url user_signin %}">{% trans "back to login" %}</a></div>
        </fieldset>
            <br >
    </form>
    <br >
    <div style="display:none">
    <h2 class="signup">{% trans "Register with your OpenID" %}</h2>
    <form name="fopenid" action="{% url user_signin %}" method="post">
        <div class="form-row">{{ form2.openid_url }}</div>
        <div class="submit-row "><input name="bsignin" class="submit" type="submit" value="{% trans "Login with your OpenID" %}"></div>
    </form>
    </div>
{% endblock %}
<!--end signup.html-->