urls.py
import os.path
from django.conf.urls.defaults import *
from django.contrib import admin
from forum.views import index
from forum import views as app
from forum.feed import RssLastestQuestionsFeed

admin.autodiscover()
feeds = {
    'rss': RssLastestQuestionsFeed
}

APP_PATH = os.path.dirname(__file__)
urlpatterns = patterns('',
    (r'^$', index),
    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/content/images/favicon.ico'}),
    (r'^favicon\.gif$', 'django.views.generic.simple.redirect_to', {'url': '/content/images/favicon.gif'}),
    (r'^content/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': os.path.join(APP_PATH, 'templates/content').replace('\\','/')}
    ),
    (r'^upfiles/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': os.path.join(APP_PATH, 'templates/upfiles').replace('\\','/')}
    ),
    (r'^account/', include('django_authopenid.urls')),
    (r'^signin/$', 'django_authopenid.views.signin'),
    url(r'^email/change/$', 'django_authopenid.views.changeemail', name='user_changeemail'),
    url(r'^email/sendkey/$', 'django_authopenid.views.send_email_key'),
    url(r'^email/verify/(?P<id>\d+)/(?P<key>[\dabcdef]{32})/$', 'django_authopenid.views.verifyemail', name='user_verifyemail'),
    url(r'^about/$', app.about, name='about'),
    url(r'^faq/$', app.faq, name='faq'),
    url(r'^privacy/$', app.privacy, name='privacy'),
    url(r'^logout/$', app.logout, name='logout'),
    url(r'^answers/(?P<id>\d+)/comments/$', app.answer_comments, name='answer_comments'),
    url(r'^answers/(?P<id>\d+)/edit/$', app.edit_answer, name='edit_answer'),
    url(r'^answers/(?P<id>\d+)/revisions/$', app.answer_revisions, name='answer_revisions'),
    url(r'^questions/$', app.questions, name='questions'),
    url(r'^questions/ask/$', app.ask, name='ask'),
    url(r'^questions/unanswered/$', app.unanswered, name='unanswered'),
    url(r'^questions/(?P<id>\d+)/edit/$', app.edit_question, name='edit_question'),
    url(r'^questions/(?P<id>\d+)/close/$', app.close, name='close'),
    url(r'^questions/(?P<id>\d+)/reopen/$', app.reopen, name='reopen'),
    url(r'^questions/(?P<id>\d+)/answer/$', app.answer, name='answer'),
    url(r'^questions/(?P<id>\d+)/vote/$', app.vote, name='vote'),
    url(r'^questions/(?P<id>\d+)/revisions/$', app.question_revisions, name='question_revisions'),
    url(r'^questions/(?P<id>\d+)/comments/$', app.question_comments, name='question_comments'),
    url(r'^questions/(?P<question_id>\d+)/comments/(?P<comment_id>\d+)/delete/$', app.delete_question_comment, name='delete_question_comment'),
    url(r'^answers/(?P<answer_id>\d+)/comments/(?P<comment_id>\d+)/delete/$', app.delete_answer_comment, name='delete_answer_comment'),
    #place general question item in the end of other operations
    url(r'^questions/(?P<id>\d+)//*', app.question, name='question'),
    (r'^tags/$', app.tags),
    (r'^tags/(?P<tag>[^/]*)/$', app.tag),
    (r'^users/$',app.users),
    url(r'^users/(?P<id>\d+)/edit/$', app.edit_user, name='edit_user'),
    url(r'^users/(?P<id>\d+)//*', app.user, name='user'),
    url(r'^badges/$',app.badges, name='badges'),
    url(r'^badges/(?P<id>\d+)//*', app.badge, name='badge'),
    url(r'^messages/markread/$',app.read_message, name='read_message'),
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^nimda/(.*)', admin.site.root),
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
    (r'^upload/$', app.upload),
    url(r'^books/$', app.books, name='books'),
    url(r'^books/ask/(?P<short_name>[^/]+)/$', app.ask_book, name='ask_book'),
    url(r'^books/(?P<short_name>[^/]+)/$', app.book, name='book'),
    url(r'^search/$', app.search, name='search'),
    (r'^i18n/', include('django.conf.urls.i18n')),
)

forum/forms.py
import re
from datetime import date
from django import forms
from models import *
from const import *
from django.utils.translation import ugettext as _

class TitleField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(TitleField, self).__init__(*args, **kwargs)
        self.required = True
        self.widget = forms.TextInput(attrs={'size' : 70, 'autocomplete' : 'off'})
        self.max_length = 255
        self.label  = _('title')
        self.help_text = _('please enter a descriptive title for your question')
        self.initial = ''

    def clean(self, value):
        if len(value) < 10:
            raise forms.ValidationError(_('title must be > 10 characters'))

        return value

class EditorField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(EditorField, self).__init__(*args, **kwargs)
        self.required = True
        self.widget = forms.Textarea(attrs={'id':'editor'})
        self.label  = _('content')
        self.help_text = u''
        self.initial = ''

    def clean(self, value):
        if len(value) < 10:
            raise forms.ValidationError(_('question content must be > 10 characters'))

        return value

class TagNamesField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(TagNamesField, self).__init__(*args, **kwargs)
        self.required = True
        self.widget = forms.TextInput(attrs={'size' : 50, 'autocomplete' : 'off'})
        self.max_length = 255
        self.label  = _('tags')
        #self.help_text = _('please use space to separate tags (this enables autocomplete feature)')
        self.help_text = _('Tags are short keywords, with no spaces within. Up to five tags can be used.')
        self.initial = ''

	def clean(self, value):
		value = super(TagNamesField, self).clean(value)
		data = value.strip()
		if len(data) < 1:
			raise forms.ValidationError(_('tags are required'))
		list = data.split(' ')
		list_temp = []
		if len(list) > 5:
			raise forms.ValidationError(_('please use 5 tags or less'))
		for tag in list:
			if len(tag) > 20:
				raise forms.ValidationError(_('tags must be shorter than 20 characters'))
			#take tag regex from settings
			tagname_re = re.compile(r'[a-z0-9]+')
			if not tagname_re.match(tag):
				raise forms.ValidationError(_('please use following characters in tags: letters \'a-z\', numbers, and characters \'.-_#\''))
			# only keep one same tag
			if tag not in list_temp and len(tag.strip()) > 0:
				list_temp.append(tag)
		return u' '.join(list_temp)

class WikiField(forms.BooleanField):
    def __init__(self, *args, **kwargs):
        super(WikiField, self).__init__(*args, **kwargs)
        self.required = False
        self.label  = _('community wiki')
        self.help_text = _('if you choose community wiki option, the question and answer do not generate points and name of author will not be shown')

class EmailNotifyField(forms.BooleanField):
    def __init__(self, *args, **kwargs):
        super(EmailNotifyField, self).__init__(*args, **kwargs)
        self.required = False

class SummaryField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(SummaryField, self).__init__(*args, **kwargs)
        self.required = False
        self.widget = forms.TextInput(attrs={'size' : 50, 'autocomplete' : 'off'})
        self.max_length = 300
        self.label  = _('update summary:')
        self.help_text = _('enter a brief summary of your revision (e.g. fixed spelling, grammar, improved style, this field is optional)')

class AskForm(forms.Form):
    title  = TitleField()
    text   = EditorField()
    tags   = TagNamesField()
    wiki = WikiField()

    openid = forms.CharField(required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 40, 'class':'openid-input'}))
    user   = forms.CharField(required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    email  = forms.CharField(required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))

class AnswerForm(forms.Form):
    text   = EditorField()
    wiki   = WikiField()
    openid = forms.CharField(required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 40, 'class':'openid-input'}))
    user   = forms.CharField(required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    email  = forms.CharField(required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    email_notify = EmailNotifyField()
    def __init__(self, question, user, *args, **kwargs):
        super(AnswerForm, self).__init__(*args, **kwargs)
        self.fields['email_notify'].widget.attrs['id'] = 'question-subscribe-updates';
        if question.wiki:
            self.fields['wiki'].initial = True
        if user.is_authenticated():
            try:
                feed = EmailFeed.objects.get(feed_id=question.id, subscriber_id=user.id)
                if feed.subscriber == user and feed.content == question:
                    self.fields['email_notify'].initial = True
                    return
            except EmailFeed.DoesNotExist:
                pass
        self.fields['email_notify'].initial = False


class CloseForm(forms.Form):
    reason = forms.ChoiceField(choices=CLOSE_REASONS)

class RetagQuestionForm(forms.Form):
    tags   = TagNamesField()
    # initialize the default values
    def __init__(self, question, *args, **kwargs):
        super(RetagQuestionForm, self).__init__(*args, **kwargs)
        self.fields['tags'].initial = question.tagnames

class RevisionForm(forms.Form):
    """
    Lists revisions of a Question or Answer
    """
    revision = forms.ChoiceField(widget=forms.Select(attrs={'style' : 'width:520px'}))

    def __init__(self, post, latest_revision, *args, **kwargs):
        super(RevisionForm, self).__init__(*args, **kwargs)
        revisions = post.revisions.all().values_list(
            'revision', 'author__username', 'revised_at', 'summary')
        date_format = '%c'
        self.fields['revision'].choices = [
            (r[0], u'%s - %s (%s) %s' % (r[0], r[1], r[2].strftime(date_format), r[3]))
            for r in revisions]
        self.fields['revision'].initial = latest_revision.revision

class EditQuestionForm(forms.Form):
    title  = TitleField()
    text   = EditorField()
    tags   = TagNamesField()
    summary = SummaryField()

    def __init__(self, question, revision, *args, **kwargs):
        super(EditQuestionForm, self).__init__(*args, **kwargs)
        self.fields['title'].initial = revision.title
        self.fields['text'].initial = revision.text
        self.fields['tags'].initial = revision.tagnames
        # Once wiki mode is enabled, it can't be disabled
        if not question.wiki:
            self.fields['wiki'] = WikiField()

class EditAnswerForm(forms.Form):
    text = EditorField()
    summary = SummaryField()

    def __init__(self, answer, revision, *args, **kwargs):
        super(EditAnswerForm, self).__init__(*args, **kwargs)
        self.fields['text'].initial = revision.text

class EditUserForm(forms.Form):
    email = forms.EmailField(label=u'Email', help_text=_('this email does not have to be linked to gravatar'), required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    realname = forms.CharField(label=_('Real name'), required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    website = forms.URLField(label=_('Website'), required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    city = forms.CharField(label=_('Location'), required=False, max_length=255, widget=forms.TextInput(attrs={'size' : 35}))
    birthday = forms.DateField(label=_('Date of birth'), help_text=_('will not be shown, used to calculate age, format: YYYY-MM-DD'), required=False, widget=forms.TextInput(attrs={'size' : 35}))
    about = forms.CharField(label=_('Profile'), required=False, widget=forms.Textarea(attrs={'cols' : 60}))

    def __init__(self, user, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.fields['email'].initial = user.email
        self.fields['realname'].initial = user.real_name
        self.fields['website'].initial = user.website
        self.fields['city'].initial = user.location

        if user.date_of_birth is not None:
            self.fields['birthday'].initial = user.date_of_birth
        else:
            self.fields['birthday'].initial = '1990-01-01'
        self.fields['about'].initial = user.about
        self.user = user

    def clean_email(self):
        """For security reason one unique email in database"""
        if self.user.email != self.cleaned_data['email']:
            #todo dry it, there is a similar thing in openidauth
            if settings.EMAIL_UNIQUE == True:
                if 'email' in self.cleaned_data:
                    try:
                        user = User.objects.get(email = self.cleaned_data['email'])
                    except User.DoesNotExist:
                        return self.cleaned_data['email']
                    except User.MultipleObjectsReturned:
                        raise forms.ValidationError(_('this email has already been registered, please use another one'))
                    raise forms.ValidationError(_('this email has already been registered, please use another one'))
        return self.cleaned_data['email']

templates/answer_edit_tips.html
<!-- template answer_edit_tips.html -->
{% load i18n %}
<div class="boxC">
    <p class="subtitle darkred">{% trans "answer tips" %}</p>
    <div>
        <ul class="list-item">
            <li> <b>{% trans "please make your answer relevant to this community" %}</b>
            </li>
            <li>
                {% trans  "try to give an answer, rather than engage into a discussion" %}
            </li>
            <li>
                {% trans "please try to provide details" %}
            </li>
            <li>
				{% trans "be clear and concise" %}
            </li>
        </ul>
         <a href="/faq/" target="_blank" title="{% trans "see frequently asked questions" %}" style="float:right;position:relative">faq »</a>
         <br>  
    </div>
</div>

<div class="boxC">
    <p class="subtitle">{% trans "Markdown tips" %}</p>
    <ul class="list-item">
        <li>
            {% trans "*italic* or __italic__" %}
        </li>
        <li>
			{% trans "**bold** or __bold__" %}
        </li>
        <li>
            <b>{% trans "link" %}</b>:[{% trans "text" %}](http://url.com/ "{% trans "title" %}")

        </li>
        <li>
            <b>{% trans "image" %}</b>:![alt {% trans "text" %}](/path/img.jpg "{% trans "title" %}")

        </li>
        <li>
			{% trans "numbered list:" %}
            1.  Foo
            2.  Bar
        </li>
        <li>
			{% trans "basic HTML tags are also supported" %}
        </li>
    </ul>
    <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank" style="float:right;position:relative">{% trans "learn more about Markdown" %} »</a>
    <br>  
</div>
<!-- end template answer_edit_tips.html -->

templates/ask.html
{% extends "base.html" %}
<!-- template ask.html -->
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Ask a question" %}{% endspaceless %}{% endblock %}
{% block forejs %}
        <script type='text/javascript' src='/content/js/com.cnprog.editor.js'></script>
        <script type='text/javascript' src='/content/js/com.cnprog.post.js'></script>
        <script type='text/javascript' src='/content/js/jquery.validate.pack.js'></script>
        <script type='text/javascript' src='/content/js/wmd/showdown.js'></script>
        <script type='text/javascript' src='/content/js/wmd/wmd.js'></script>
        <link rel="stylesheet" type="text/css" href="/content/js/wmd/wmd.css" />
        <script type="text/javascript">
        $().ready(function(){
            //set current module button style
            $("#nav_ask").attr('className',"on");
            $('#editor').TextAreaResizer();

            //highlight code synctax when editor has new text
            $("#editor").typeWatch({highlight: false, wait: 3000,
                             captureLength: 5, callback: lanai.highlightSyntax});

            //toggle preview of editor
			//todo remove copy-paste
            var display = true;
            var txt = "[{% trans "hide preview" %}]";
            $('#pre-collapse').text(txt);
            $('#pre-collapse').bind('click', function(){
                txt = display ? "[{% trans "show preview" %}]" : "[{% trans "hide preview" %}]";
                display = !display;
                $('#previewer').toggle();
                $('#pre-collapse').text(txt);
            });

            //Tags autocomplete action
            var tags = {{ tags|safe }};
        	$("#id_tags").autocomplete(tags, {
                minChars: 1,
        		matchContains: true,
                max: 20,
                multiple: true,
                multipleSeparator: " ",
        		formatItem: function(row, i, max) {
        			return row.n + " ("+ row.c +")";
        		},
                formatResult: function(row, i, max){
                    return row.n;
                }

            });

            setupFormValidation("#fmask", CPValidator.getQuestionFormRules(), CPValidator.getQuestionFormMessages());
            lanai.highlightSyntax();

        });
        </script>
{% endblock %}

{% block content %}
<div id="main-bar" class="headNormal">
	{% trans "Ask a question" %}
</div>
<div id="main-body" class="ask-body">
    <div id="askform">
        <form id="fmask" action="" method="post" >
			{% if not request.user.is_authenticated %}
            <div class="message">
			    <p>{% trans "login to post question info" %}</p>
            </div>
            {% else %}
                {% ifequal settings.EMAIL_VALIDATION 'on' %}
                    {% if not request.user.email_isvalid %}
                        <div class="message">
                            {% blocktrans with request.user.email as email %}must have valid {{email}} to post{% endblocktrans %}
                        </div>
                    {% endif %}
                {% endifequal %}
			{% endif %}
            <p class="form-item">
                <label for="id_title" ><strong>{{ form.title.label_tag }}:</strong></label> <span class="form-error"></span><br>
                {{ form.title }} {{ form.title.errors }}
                <div class="title-desc">
                    {{ form.title.help_text }}
                </div>
            </p>

            <p class="form-item">
                <div id="wmd-button-bar" class="wmd-panel"></div>
                {{ form.text }}

                <div class="preview-toggle">
                    <table width="100%">
                        <tr>
                            <td>
                                <span id="pre-collapse" title="{% trans "Toggle the real time Markdown editor preview" %}">{% trans "toggle preview" %}</span>
                            </td>
                            <td style="text-align:right;">
                                {{ form.wiki }} <span style="font-weight:normal;cursor:help" title="{{form.wiki.help_text}}">{{ form.wiki.label_tag }} </span>
                            </td>
                        </tr>

                    </table>
                </div>
                <div id="previewer" class="wmd-preview"></div>
                <span class="form-error"></span>
                <br>
            </p>
            <p class="form-item">
                <strong>{{ form.tags.label_tag }}:</strong> {% trans "(required)" %} <span class="form-error"></span><br>
                {{ form.tags }}  {{ form.tags.errors }}
            </p>
			<p class="title-desc">
				{{ form.tags.help_text }}
			</p>
            {% if not request.user.is_authenticated %}
            <input type="submit" value="{% trans "Login/signup to post your question" %}" class="submit" />
			{% else %}
            <input type="submit" value="{% trans "Ask your question" %}" class="submit" />
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

{% block sidebar %}
{% include "question_edit_tips.html" %}
{% endblock %}

{% block endjs %}
{% endblock %}
<!-- end template ask.html -->

templates/footer.html
<!-- template footer.html -->
{% load extra_tags %}
{% load i18n %}
<!-- 页面底部开始： -->
    <div id="ground">
        <div class="footerLinks" >
            <a href="/about">{% trans "about" %}</a><span class="link-separator"> |</span>
            <a href="/faq">{% trans "faq" %}</a><span class="link-separator"> |</span>
            <a href="http://blog.codigodemaquina.org{{ blog_url }}">{% trans "blog" %}</a><span class="link-separator"> |</span>
            <a href="{{ webmaster_email }}">{% trans "contact us" %}</a><span class="link-separator"> |</span>
            <a href="/privacy">{% trans "privacy policy" %}</a><span class="link-separator"> |</span>
            <a href="/feeds/rss/">RSS</a><span class="link-separator"> |</span>
            <a href="http://codigodemaquina.uservoice.com{{ feedback_url }}" target="_blank">{% trans "give feedback" %}</a>
        </div>
	  <p style="margin-top:10px;">
         <a href="http://bananaorange.com/" target="_blank">
            <img src="/content/images/banner-120x60.png" border="0" alt="Made with Django." title="Made with Django." >
         </a>
         <!--<div style="font-size:90%;color:#333">{% trans "current revision" %}: R-0120-20090406</div>-->
      </p>
	  <p id="licenseLogo"><img src="/content/images/cc-wiki.png" title="Creative Commons: Attribution - Share Alike" alt="cc-wiki" width="50" height="68" /></p>
	</div>
	<!-- 页面底部结束： -->
        <script type="text/javascript">
            var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
            document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
            </script>
            <script type="text/javascript">
            try {
            var pageTracker = _gat._getTracker({{ settings.GOOGLE_ANALYTICS_KEY }});
            pageTracker._trackPageview();
            } catch(err) {}
        </script>
<!-- end template footer.html -->

templates/question_edit.html
{% extends "base.html" %}
<!-- question_edit.html -->
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Edit question" %}{% endspaceless %}{% endblock %}
{% block forejs %}
        <script type='text/javascript' src='/content/js/com.cnprog.editor.js'></script>
        <script type='text/javascript' src='/content/js/com.cnprog.post.js'></script>
        <script type='text/javascript' src='/content/js/jquery.validate.pack.js'></script>
        <script type='text/javascript' src='/content/js/wmd/showdown.js'></script>
        <script type='text/javascript' src='/content/js/wmd/wmd.js'></script>
        <link rel="stylesheet" type="text/css" href="/content/js/wmd/wmd.css" />
        <script type="text/javascript">
		//todo move javascript out        
        $().ready(function(){
            $("#nav_questions").attr('className',"on");
            $('#editor').TextAreaResizer();
            
            //highlight code synctax when editor has new text
            $("#editor").typeWatch({highlight: false, wait: 3000,
                             captureLength: 5, callback: lanai.highlightSyntax});
                             
            //toggle preview of editor
            var display = true;
            var txt = "[{% trans "hide preview"}%]";
            $('#pre-collapse').text(txt);
            $('#pre-collapse').bind('click', function(){
                txt = display ? "[{% trans "show preview" %}]" : "[{% trans "hide preview" %}]";
                display = !display;
                $('#previewer').toggle();
                $('#pre-collapse').text(txt);
            });
            
            //Tags autocomplete action
            var tags = {{ tags|safe }};
        	$("#id_tags").autocomplete(tags, {
        		matchContains: true,
                max: 20,
                multiple: true,
                multipleSeparator: " ",
                highlightItem: true,
                scroll: true,
                scrollHeight: 300,
        		formatItem: function(row, i, max) {
        			return row.n + " ("+ row.c +")";
        		},
                formatResult: function(row, i, max){
                    return row.n;
                }
                
            });
            
            setupFormValidation("#fmedit", CPValidator.getQuestionFormRules(), CPValidator.getQuestionFormMessages());
            
            $('#id_revision').unbind().change(function(){
                $("#select_revision").click();
            });
            lanai.highlightSyntax();
            
        });
        </script>
{% endblock %}
        
{% block content %}
<div id="main-bar" class="headNormal">
    {% trans "Edit question" %} [<a href="{{ question.get_absolute_url }}">{% trans "back" %}</a>]
</div>
<div id="main-body" class="ask-body">
    <div id="askform">
        <form id="fmedit" action="{% url edit_question question.id %}" method="post" >
            <label for="id_revision" ><strong>{% trans "revision" %}:</strong></label> <br> 
            {% if revision_form.revision.errors %}{{ revision_form.revision.errors.as_ul }}{% endif %}
            <div style="vertical-align:middle">
            {{ revision_form.revision }} <input type="submit" style="display:none" id="select_revision" name="select_revision" 
											value="{% trans "select revision"%}">
            </div><br> 
            <div class="form-item">
                <label for="id_title" ><strong>{{ form.title.label_tag }}:</strong></label> <span class="form-error"></span><br> 
                {{ form.title }} {{ form.title.errors }}  
                <div class="title-desc">
                    {{ form.title.help_text }}
                </div>     
            </div>
            <div class="form-item">
                <div id="wmd-button-bar" class="wmd-panel"></div>
                {{ form.text }}
                <span class="form-error"></span>
                <div class="preview-toggle">
                    <table width="100%">
                        <tr>
                            <td>
                                <span id="pre-collapse" title="{% trans "Toggle the real time Markdown editor preview" %}">{% trans "toggle preview" %}</span>
                            </td>
                            <td style="text-align:right;">
                                {{ form.wiki }} <span style="color:#000;cursor:help" title="{{form.wiki.help_text}}">{{ form.wiki.label_tag }} </span>
                            </td>
                        </tr>
                    
                    </table>   
                </div>
                <div id="previewer" class="wmd-preview"></div>
                <br>
            </div>
            <div class="form-item">
                <strong>{{ form.tags.label_tag }}:</strong> <span class="form-error"></span><br>
                {{ form.tags }}  {{ form.tags.errors }}
                <div class="title-desc">
                    {{ form.tags.help_text }}
                </div>
            </div>
            <br>
            <strong>{{ form.summary.label_tag }}</strong> <br>
            {{ form.summary }}  {{ form.summary.errors }}
            <div class="title-desc">
                {{ form.summary.help_text }}
            </div>
            <br>

            <div class="error" ></div>
            <input type="submit" value="{% trans "Save edit" %}" class="submit" />
            <input type="button" value="{% trans "Cancel" %}" class="submit" onclick="history.back(-1);" />
            <br>
            <br>
        </form>
    </div>
</div>
{% endblock %}

{% block sidebar %}
{% include "question_edit_tips.html" %}
{% endblock %}

{% block endjs %}
{% endblock %}
<!-- end question_edit.html -->

templates/tags.html
{% extends "base_content.html" %}
<!-- tags.html -->
{% load i18n %}
{% load extra_tags %}
{% load humanize %}
{% block title %}{% spaceless %}{% trans "Tag list" %}{% endspaceless %}{% endblock %}
{% block forejs %}
       <script type="text/javascript">
        $().ready(function(){
            $("#nav_tags").attr('className',"on");
            $("#ipSearchTag").focus();

            var orderby = "{{ tab_id }}";
            if(orderby != "used" && orderby != "name")
                orderby = "used";
            $("#sort_" + orderby).attr('className',"on");
            $("#type-tag").attr('checked',true);

            Hilite.exact = false;
            Hilite.elementid = "searchtags";
            Hilite.debug_referrer = location.href;
        });

        </script>
{% endblock %}
{% block content %}
<!-- Tabs -->
<div class="tabBar">
    <div class="headQuestions">{% trans "Tag list" %}</div>
    <div class="tabsA">
        <a id="sort_name" href="/tags/?sort=name" class="off" title="{% trans "sorted alphabetically" %}">{% trans "by name" %}</a>
        <a id="sort_used" href="/tags/?sort=used" class="off" title="{% trans "sorted by frequency of tag use" %}">{% trans "by popularity" %}</a>
    </div>
</div>
<div id="searchtags">
<p>
{% if stag %}
    {% trans "All tags matching query" %} '<span class="darkred"><strong>{{ stag }}</strong></span>' {% trans "all tags - make this empty in english" %}:
{% endif %}
{% if not tags.object_list %}
    <span>{% trans "Nothing found" %}</span>
{% endif %}
</p>
<ul class="tagsList tags">
{% for tag in tags.object_list %}
   <li>
    <a href="{% url forum.views.tag tag|urlencode %}" title="{% trans "see questions tagged" %}'{{ tag }}'{% trans "using tags" %}" rel="tag">
        {{ tag }}
    </a>&nbsp;
    <span class="tag-number">× {{ tag.used_count|intcomma }}</span>
    <br>

    </li>
{% endfor %}
</ul>
</div>

{% endblock %}
{% block tail %}
<div class="pager">
    {% cnprog_paginator context %}
</div>              
{% endblock %}
<!-- end tags.html -->

templates/user_footer.html
<!-- user_footer.html -->
<div id="mainbar-footer">

</div><!-- end user_footer.html -->